# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_service.proto\"2\n\rUploadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"!\n\x0eUploadResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x0f\x44ownloadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"5\n\x10\x44ownloadResponse\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x32q\n\x0b\x46ileService\x12-\n\nUploadFile\x12\x0e.UploadRequest\x1a\x0f.UploadResponse\x12\x33\n\x0c\x44ownloadFile\x12\x10.DownloadRequest\x1a\x11.DownloadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADREQUEST']._serialized_start=22
  _globals['_UPLOADREQUEST']._serialized_end=72
  _globals['_UPLOADRESPONSE']._serialized_start=74
  _globals['_UPLOADRESPONSE']._serialized_end=107
  _globals['_DOWNLOADREQUEST']._serialized_start=109
  _globals['_DOWNLOADREQUEST']._serialized_end=144
  _globals['_DOWNLOADRESPONSE']._serialized_start=146
  _globals['_DOWNLOADRESPONSE']._serialized_end=199
  _globals['_FILESERVICE']._serialized_start=201
  _globals['_FILESERVICE']._serialized_end=314
# @@protoc_insertion_point(module_scope)
