#!/usr/bin/bash

echo "From: $1" | cat > mail.txt
echo "To: $2" >> mail.txt
echo "Cc: $3" >> mail.txt
echo "Subject: $4" >> mail.txt
echo " This email is generated by my shell script." >> mail.txt
echo "Thanks and regards" >> mail.txt
echo "S4 CSE student" >> mail.txt
echo "Amritapuri" >> mail.txt
cat mail.txt