/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADD_H_RPCGEN
#define _ADD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct add_in {
	long arg1;
	long arg2;
};
typedef struct add_in add_in;

struct sub_in {
	long arg1;
	long arg2;
};
typedef struct sub_in sub_in;

typedef long add_out;

typedef long sub_out;

#define ADD_PROG 0x3543000
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD_PROC 1
extern  add_out * add_proc_1(add_in *, CLIENT *);
extern  add_out * add_proc_1_svc(add_in *, struct svc_req *);
#define SUB_PROC 2
extern  sub_out * sub_proc_1(sub_in *, CLIENT *);
extern  sub_out * sub_proc_1_svc(sub_in *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD_PROC 1
extern  add_out * add_proc_1();
extern  add_out * add_proc_1_svc();
#define SUB_PROC 2
extern  sub_out * sub_proc_1();
extern  sub_out * sub_proc_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_add_in (XDR *, add_in*);
extern  bool_t xdr_sub_in (XDR *, sub_in*);
extern  bool_t xdr_add_out (XDR *, add_out*);
extern  bool_t xdr_sub_out (XDR *, sub_out*);

#else /* K&R C */
extern bool_t xdr_add_in ();
extern bool_t xdr_sub_in ();
extern bool_t xdr_add_out ();
extern bool_t xdr_sub_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADD_H_RPCGEN */
