/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "add.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

add_out *
add_proc_1(add_in *argp, CLIENT *clnt)
{
	static add_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ADD_PROC,
		(xdrproc_t) xdr_add_in, (caddr_t) argp,
		(xdrproc_t) xdr_add_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

sub_out *
sub_proc_1(sub_in *argp, CLIENT *clnt)
{
	static sub_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SUB_PROC,
		(xdrproc_t) xdr_sub_in, (caddr_t) argp,
		(xdrproc_t) xdr_sub_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
