// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: standalone.flex

import java.util.*;


@SuppressWarnings("fallthrough")
public class q {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\3\3\22\0\1\4\1\5\1\0"+
    "\1\6\1\0\1\7\1\10\1\0\1\11\1\12\1\13"+
    "\1\14\1\0\1\15\1\16\1\17\12\20\1\21\1\22"+
    "\1\23\1\24\1\25\2\0\32\26\1\11\1\0\1\12"+
    "\1\27\2\0\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\26\1\36\1\37\1\26\1\40\1\41\1\26\1\42"+
    "\1\43\1\44\1\26\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\3\26\1\11\1\53\1\12\7\0\1\3\u01a2\0"+
    "\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\1\6"+
    "\1\7\1\10\2\5\1\6\1\5\1\11\1\12\1\13"+
    "\1\14\1\5\1\14\1\1\1\15\12\1\1\15\1\14"+
    "\3\0\1\4\1\5\1\0\1\16\2\0\1\15\1\17"+
    "\7\20\1\21\6\20\12\0\1\22\1\23\1\0\5\20"+
    "\1\24\5\20\10\0\1\25\1\0\5\20\3\0\1\16"+
    "\1\25\1\16\4\20\1\0\1\26\1\0\1\20";

  private static int [] zzUnpackAction() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\54\0\130\0\204\0\260\0\54\0\334"+
    "\0\54\0\54\0\u0108\0\u0134\0\54\0\u0160\0\u018c\0\54"+
    "\0\54\0\u01b8\0\u01e4\0\u0210\0\u023c\0\54\0\u0268\0\u0294"+
    "\0\u02c0\0\u02ec\0\u0318\0\u0344\0\u0370\0\u039c\0\u03c8\0\u03f4"+
    "\0\u0420\0\54\0\u044c\0\u0478\0\u04a4\0\54\0\u04d0\0\u04fc"+
    "\0\u0528\0\u0554\0\u0580\0\u05ac\0\54\0\u023c\0\u05d8\0\u0604"+
    "\0\u0630\0\u065c\0\u0688\0\u06b4\0\u023c\0\u06e0\0\u070c\0\u0738"+
    "\0\u0764\0\u0790\0\u07bc\0\u07e8\0\u0814\0\u0840\0\u086c\0\u04d0"+
    "\0\u0898\0\u08c4\0\u08f0\0\u091c\0\u0948\0\u0554\0\54\0\u05ac"+
    "\0\u0974\0\u09a0\0\u09cc\0\u09f8\0\u0a24\0\u023c\0\u0a50\0\u0a7c"+
    "\0\u0aa8\0\u0ad4\0\u0b00\0\u0b2c\0\u0b58\0\u0b84\0\u0bb0\0\u0bdc"+
    "\0\u0c08\0\u0c34\0\u0c60\0\u0898\0\u0c8c\0\u0cb8\0\u0ce4\0\u0d10"+
    "\0\u0d3c\0\u0d68\0\u0d94\0\u0dc0\0\u0dec\0\u0898\0\u0c34\0\u0948"+
    "\0\u0e18\0\u0e44\0\u0e70\0\u0e9c\0\u0ec8\0\54\0\u0ef4\0\u0f20";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\7\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\25\1\27"+
    "\1\30\1\25\1\31\1\32\1\25\1\33\4\25\1\34"+
    "\1\35\1\36\2\25\1\37\1\40\1\41\60\0\1\4"+
    "\73\0\1\42\62\0\1\43\1\44\2\0\1\45\24\0"+
    "\1\46\57\0\1\7\54\0\1\47\2\0\1\17\4\0"+
    "\1\15\41\0\1\50\3\0\1\51\52\0\1\52\1\0"+
    "\1\17\51\0\1\53\4\0\1\54\1\55\1\0\1\53"+
    "\1\0\23\53\25\0\1\55\53\0\1\55\1\26\46\0"+
    "\1\56\5\0\1\56\1\0\23\56\21\0\1\56\5\0"+
    "\1\56\1\0\15\56\1\57\5\56\21\0\1\56\5\0"+
    "\1\56\1\0\1\60\5\56\1\61\4\56\1\62\7\56"+
    "\21\0\1\56\5\0\1\56\1\0\11\56\1\60\11\56"+
    "\21\0\1\56\5\0\1\56\1\0\11\56\1\63\1\56"+
    "\1\64\7\56\21\0\1\56\5\0\1\56\1\0\5\56"+
    "\1\65\4\56\1\66\10\56\21\0\1\56\5\0\1\56"+
    "\1\0\15\56\1\67\5\56\21\0\1\56\5\0\1\56"+
    "\1\0\4\56\1\70\16\56\21\0\1\56\5\0\1\56"+
    "\1\0\22\56\1\71\21\0\1\56\5\0\1\56\1\0"+
    "\13\56\1\72\7\56\21\0\1\56\5\0\1\56\1\0"+
    "\6\56\1\73\14\56\54\0\1\46\34\0\1\74\61\0"+
    "\1\75\46\0\1\76\4\0\1\77\26\0\1\100\2\0"+
    "\1\17\33\0\1\101\1\102\1\103\1\0\7\101\1\104"+
    "\3\101\1\105\34\101\2\51\2\0\50\51\20\0\1\106"+
    "\51\0\1\53\6\0\1\107\1\53\1\0\23\53\17\0"+
    "\1\53\4\0\1\110\2\0\1\53\1\0\23\53\21\0"+
    "\1\56\5\0\1\56\1\0\4\56\1\111\16\56\21\0"+
    "\1\56\5\0\1\56\1\0\16\56\1\112\4\56\21\0"+
    "\1\56\5\0\1\56\1\0\1\113\22\56\21\0\1\56"+
    "\5\0\1\56\1\0\12\56\1\114\10\56\21\0\1\56"+
    "\5\0\1\56\1\0\13\56\1\115\7\56\21\0\1\56"+
    "\5\0\1\56\1\0\15\56\1\65\5\56\21\0\1\56"+
    "\5\0\1\56\1\0\17\56\1\116\3\56\21\0\1\56"+
    "\5\0\1\56\1\0\7\56\1\117\13\56\21\0\1\56"+
    "\5\0\1\56\1\0\17\56\1\120\3\56\21\0\1\56"+
    "\5\0\1\56\1\0\7\56\1\121\13\56\21\0\1\56"+
    "\5\0\1\56\1\0\7\56\1\122\13\56\21\0\1\56"+
    "\5\0\1\56\1\0\7\56\1\123\13\56\36\0\1\124"+
    "\51\0\1\125\53\0\1\126\6\0\1\127\43\0\1\130"+
    "\21\0\1\101\1\102\1\103\1\0\7\101\1\131\41\101"+
    "\1\102\1\103\1\0\7\101\1\104\40\101\1\132\2\103"+
    "\1\0\7\132\1\133\40\132\1\101\1\102\1\103\1\0"+
    "\7\101\1\131\3\101\1\134\35\101\1\102\1\103\1\0"+
    "\7\101\1\135\40\101\20\0\1\56\5\0\1\56\1\0"+
    "\1\136\22\56\21\0\1\56\5\0\1\56\1\0\4\56"+
    "\1\65\16\56\21\0\1\56\5\0\1\56\1\0\15\56"+
    "\1\116\5\56\21\0\1\56\5\0\1\56\1\0\17\56"+
    "\1\137\3\56\21\0\1\56\5\0\1\56\1\0\1\66"+
    "\22\56\21\0\1\56\5\0\1\56\1\0\12\56\1\140"+
    "\10\56\21\0\1\56\5\0\1\56\1\0\20\56\1\141"+
    "\2\56\21\0\1\56\5\0\1\56\1\0\17\56\1\142"+
    "\3\56\21\0\1\56\5\0\1\56\1\0\3\56\1\65"+
    "\17\56\21\0\1\56\5\0\1\56\1\0\11\56\1\112"+
    "\11\56\40\0\1\143\53\0\1\144\50\0\1\144\52\0"+
    "\1\126\61\0\1\145\12\0\1\101\1\102\1\103\1\0"+
    "\7\101\1\131\3\101\1\146\34\101\1\132\2\103\1\0"+
    "\51\132\2\103\1\0\13\132\1\147\34\132\1\101\1\102"+
    "\1\103\1\0\7\101\1\104\3\101\1\150\34\101\20\0"+
    "\1\56\5\0\1\56\1\0\10\56\1\65\12\56\21\0"+
    "\1\56\5\0\1\56\1\0\7\56\1\151\13\56\21\0"+
    "\1\56\5\0\1\56\1\0\17\56\1\152\3\56\21\0"+
    "\1\56\5\0\1\56\1\0\15\56\1\153\5\56\21\0"+
    "\1\56\5\0\1\56\1\0\2\56\1\154\20\56\43\0"+
    "\1\155\46\0\1\156\66\0\1\157\23\0\1\56\5\0"+
    "\1\56\1\0\12\56\1\160\10\56\21\0\1\56\5\0"+
    "\1\56\1\0\5\56\1\65\15\56\21\0\1\56\5\0"+
    "\1\56\1\0\12\56\1\65\10\56\21\0\1\56\5\0"+
    "\1\56\1\0\6\56\1\65\14\56\35\0\1\156\52\0"+
    "\1\155\40\0\1\56\5\0\1\56\1\0\20\56\1\112"+
    "\2\56\1\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3916];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\1\11\1\1\2\11\2\1\1\11"+
    "\2\1\2\11\4\1\1\11\13\1\1\11\3\0\1\11"+
    "\1\1\1\0\1\1\2\0\1\1\1\11\16\1\12\0"+
    "\1\1\1\11\1\0\13\1\10\0\1\1\1\0\5\1"+
    "\3\0\7\1\1\0\1\11\1\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public q(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.printf("%-30s ERROR\n", yytext());
            }
          // fall through
          case 23: break;
          case 2:
            { System.out.print(yytext());
            }
          // fall through
          case 24: break;
          case 3:
            { System.out.printf("%-30s WHITESPACE\n", yytext());
            }
          // fall through
          case 25: break;
          case 4:
            { System.out.printf("%-30s BOOLEAN OPERATORS\n", yytext());
            }
          // fall through
          case 26: break;
          case 5:
            { System.out.printf("%-30s ARTHEMETIC OPERATORS\n", yytext());
            }
          // fall through
          case 27: break;
          case 6:
            { System.out.printf("%-30s POINTER OPERATORS\n", yytext());
            }
          // fall through
          case 28: break;
          case 7:
            { System.out.printf("%-30s PARANTHESES - OPENING\n", yytext());
            }
          // fall through
          case 29: break;
          case 8:
            { System.out.printf("%-30s PARANTHESES - CLOSING\n", yytext());
            }
          // fall through
          case 30: break;
          case 9:
            { System.out.printf("%-30s INTEGER\n", yytext());
            }
          // fall through
          case 31: break;
          case 10:
            { System.out.printf("%-30s COLON\n", yytext());
            }
          // fall through
          case 32: break;
          case 11:
            { System.out.printf("%-30s SEMICOLON\n", yytext());
            }
          // fall through
          case 33: break;
          case 12:
            { System.out.printf("%-30s COMPARASION OPERATORS\n", yytext());
            }
          // fall through
          case 34: break;
          case 13:
            { System.out.printf("%-30s BITWISE OPERATORS\n", yytext());
            }
          // fall through
          case 35: break;
          case 14:
            { System.out.printf("%-30s COMMENTS\n", yytext());
            }
          // fall through
          case 36: break;
          case 15:
            { System.out.printf("%-30s COMPARASION OPERATORS WITH EQUALITY\n", yytext());
            }
          // fall through
          case 37: break;
          case 16:
            { System.out.printf("%-30s IDENTIFIER\n", yytext());
            }
          // fall through
          case 38: break;
          case 17:
            { System.out.printf("%-30s KEYWORD\n", yytext());
            }
          // fall through
          case 39: break;
          case 18:
            { System.out.printf("%-30s FLOATING POINT\n", yytext());
            }
          // fall through
          case 40: break;
          case 19:
            { System.out.printf("%-30s HEADER FILE\n", yytext());
            }
          // fall through
          case 41: break;
          case 20:
            { System.out.printf("%-30s DATA TYPES\n", yytext());
            }
          // fall through
          case 42: break;
          case 21:
            { System.out.printf("%-30s MULTILINE COMMENTS\n", yytext());
            }
          // fall through
          case 43: break;
          case 22:
            { System.out.printf("%-30s MACROS\n", yytext());
            }
          // fall through
          case 44: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java q [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        q scanner = null;
        java.io.FileInputStream stream = null;
        java.io.Reader reader = null;
        try {
          stream = new java.io.FileInputStream(argv[i]);
          reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new q(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
        finally {
          if (reader != null) {
            try {
              reader.close();
            }
            catch (java.io.IOException e) {
              System.out.println("IO error closing file \""+argv[i]+"\"");
              System.out.println(e);
            }
          }
          if (stream != null) {
            try {
              stream.close();
            }
            catch (java.io.IOException e) {
              System.out.println("IO error closing file \""+argv[i]+"\"");
              System.out.println(e);
            }
          }
        }
      }
    }
  }


}
