# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"4\n\x10OperationRequest\x12\x0f\n\x07number1\x18\x01 \x01(\x01\x12\x0f\n\x07number2\x18\x02 \x01(\x01\"2\n\x11OperationResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xa9\x02\n\nCalculator\x12\x42\n\x03\x41\x64\x64\x12\x1c.calculator.OperationRequest\x1a\x1d.calculator.OperationResponse\x12G\n\x08Subtract\x12\x1c.calculator.OperationRequest\x1a\x1d.calculator.OperationResponse\x12G\n\x08Multiply\x12\x1c.calculator.OperationRequest\x1a\x1d.calculator.OperationResponse\x12\x45\n\x06\x44ivide\x12\x1c.calculator.OperationRequest\x1a\x1d.calculator.OperationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERATIONREQUEST']._serialized_start=32
  _globals['_OPERATIONREQUEST']._serialized_end=84
  _globals['_OPERATIONRESPONSE']._serialized_start=86
  _globals['_OPERATIONRESPONSE']._serialized_end=136
  _globals['_CALCULATOR']._serialized_start=139
  _globals['_CALCULATOR']._serialized_end=436
# @@protoc_insertion_point(module_scope)
